[features]
seeds = false
skip-lint = false

[programs.localnet]
arbitrage = "3pRCczvKX3eUmgwHpf9jLjoWykLw19CT2TXyisSweL5w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
